### ISSUE TITLE
[Help request] Updating password, then set new password as variable

### ISSUE THREAD

**Issue by likelymichael** [darrenjrobinson/1Pwd#1]
We're looking for a way to automate the process of resetting the password of an account monthly, updating it in 1Pass, and then sending an email out to a mail group alerting them of the password change and to check 1Pass. Would the first 2 work with 1Pwd PS module?

We would want to essentially do the following:

1. Take current account password and update "old password" field with current password
2. Generate a new password for account
3. Output new password into a variable
4. Change Azure account password to new generated password
5. Send email to group letting them know password was changed.

Steps 4-5, I have set up already. It's just step 1-3 that I'm unfamiliar on how to execute with 1Pwd module. I tried with using op.exe, but it seemed super convoluted, and nearly impossible to retrieve an account password without using a json module.

**Comment by likelymichael** [comment]
Need to invoke something like this:

`Invoke-1PasswordExpression "edit item TestAccount --generate-password"`
`Invoke-1PasswordExpression "edit item TestAccount Oldpassword.password=$OldPassword"`

**Comment by darrenjrobinson** [comment]
It's a bit easier than that. 

If you generate the new password you want to use you can simply update the existing vault entry with the new password and 1Pwd will automatically put the old password in the password history. 

So you could do something like this:

```powershell 
# Get Vault Entry
$1PwdItem = Invoke-1PasswordExpression "get item '1PWD Module Update Test'"

# Update the Item
Invoke-1PasswordExpression "edit item $($1PwdItem.uuid) password=mynewpassword"

# Get the Item again and look at the password history
$1PwdItem = Invoke-1PasswordExpression "get item '1PWD Module Update Test'"
$1PwdItem.details.passwordHistory 
```

**Comment by darrenjrobinson** [comment]
Forgot to add, if you want to allow 1Password to generate the new password rather than providing the value then use this syntax after retrieving the item to use the UUID for updating it. This will by default create a 32-character password made up of letters, numbers, and symbols. 

```powershell 
Invoke-1PasswordExpression "edit item $($1PwdItem.uuid) password --generate-password"
```

The old password is then available in the details.passwordHistory and the new password in details.fields which can be easily enumerated with 

```powershell 
# Get Item
$updatedItem = Invoke-1PasswordExpression "get item $($1PwdItem.uuid)"
$updatedItem.details.fields | where-object {$_.designation -eq 'password'} | select-object 
```

**Comment by likelymichael** [comment]
Thanks for the quick response! I'm trying to test your suggestions, and I keep getting this error:

```
PS C:\windows\system32> Test-1PasswordCredentials -SignInAddress $1PSignInAddress -SignInAccount $1PSignInAccount -SecretKey $1PSecretKey -MasterPassword $1PMasterPassword
Invoke-Expression : The term 'C:\Users\mclac\vscoderepo\\op.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is   
correct and try again.
At C:\Program Files\WindowsPowerShell\Modules\1Pwd\1.0.0\1Pwd.psm1:214 char:21
+ ...     return (Invoke-Expression -command "$($Global:CLiLocation)\\op.ex ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\mclac\vscoderepo\\op.exe:String) [Invoke-Expression], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.InvokeExpressionCommand
```

My system32 folder is what contains op.exe, but whenever I try running invoke-expression, it tries running it out of c:\users\...\...

Any ideas how I can change that? I'm not well versed with PS Invoke-Expression.

**Comment by darrenjrobinson** [comment]
[Put op.exe in the same directory as your script](https://github.com/darrenjrobinson/1Pwd#prerequsites)

**Comment by likelymichael** [comment]
Ok got that working. Now when trying to change the password of the account, I get this error: 
```
PS C:\windows\system32> Invoke-1PasswordExpression "edit item $($1PwdItem.uuid) password --generate-password"
[ERROR] 2021/12/22 08:19:43 Nothing changed. Assignment statement number 1 is not formatted correctly. Use: [<section>.]<field>=<value>
```
Edit:
When I run this `Invoke-1PasswordExpression "get item $($1PItem)"` I get the return of account info

Edit 2: I got it to work by modifying the cmdlet to `nvoke-1PasswordExpression "edit item $($1PwdItem.uuid) --generate-password"` I think we're good to go! Thanks for all of your help!

**Comment by darrenjrobinson** [comment]
Great you got it working. Just saw I had a typo in the commands and have updated to correct. 

The end-to-end sequence is:

```powershell 
Import-module 1Pwd
Test-1PasswordCredentials -SignInAddress $1PSignInAddress -SignInAccount $1PSignInAccount -SecretKey $1PSecretKey -MasterPassword $1PMasterPassword

# Get Vault Entry
$1PwdItem = Invoke-1PasswordExpression "get item '1PWD Module Update Test'"
$1PwdItem

# Update with new system generated password
Invoke-1PasswordExpression "edit item $($1PwdItem.uuid) --generate-password"

# Get Item and retrieve password history
$updatedItem = Invoke-1PasswordExpression "get item $($1PwdItem.uuid)"
$updatedItem.details.passwordHistory
```

OUTPUT
```powershell
uuid         : tiivikewyjlacfggnzqhyrq6a4
templateUuid : 001
trashed      : N
createdAt    : 21/12/2021 1:36:13 AM
updatedAt    : 23/12/2021 12:34:43 AM
changerUuid  : JYHK54URZVBPPNPKEMBN35PVQI
itemVersion  : 5
vaultUuid    : mwe6cfl6ipwwunwqlmpw5vjpdy
details      : @{fields=System.Object[]; htmlForm=; notesPlain=old cjdhxriCdeLuKp27Kuxw ; passwordHistory=System.Object[]; sections=System.Object[]}       
overview     : @{ainfo=myuser@mydomain.com; pbe=189.700210571289; pgrng=True; ps=100; title=1PWD Module Update Test}

time  : 1640052311
value : cjdhxriCdeLuKp27Kuxw

time  : 1640059837
value : abcdef

time  : 1640219683
value : vaZeNCZQ-H2zNLbFB-QApjmW2.bsg89B

time  : 1640219905
value : efK@XgzfxM336CWeyuTcMh7AQWq!E2m!
```
