### ISSUE TITLE
Cannot install 1Pwd module: Install-Package: The module '1Pwd' cannot be installed or updated because the authenticode signature of the file '1Pwd.psd1' is not valid. - expired certificate

### ISSUE THREAD

**Issue by wsuhoey** [darrenjrobinson/1Pwd#5]
Repro:
`Install-Module 1Pwd`

Error result:
`Install-Package: The module '1Pwd' cannot be installed or updated because the authenticode signature of the file '1Pwd.psd1' is not valid.`

`Get-OpenAuthenticodeSignature` returns: `Certificate trust could not be established. The first reported error is: certificate has expired`

Furthermore, `Get-OpenAuthenticodeSignature /1pwd/1Pwd.psd1 -SkipCertificateCheck | Select *` shows an expiration (Not After) 2023-06-19 (2 days ago)

**Comment by wsuhoey** [comment]
It's worth noting that a workaround is to do `Install-Module 1Pwd -SkipPublisherCheck` but ideally the certificate should be renewed :)

**Comment by darrenjrobinson** [comment]
Whilst the signing certificate that was used has expired (not been revoked)
the signature is still correct.

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_signing?view=powershell-7.3#prevent-the-signature-from-expiring

It looks like the timestamp server I used no longer exists. 😡
FYI http://timestamp.verisign.com/scripts/timstamp.dll

**Comment by darrenjrobinson** [comment]
@wsuhoey can you try with the updated commit above.

**Comment by wsuhoey** [comment]
Admittedly, I'm not sure how to test the commit via `Install-Module` without using the PSGallery. :(

**Comment by darrenjrobinson** [comment]
v2 is published to the PowerShell Gallery now. It supports CLI 2 as well as CLI 1. 
It is both signed with a current cert and using a timestamp server that is available for when the cert expires. 
More details here. https://darrenjrobinson.hashnode.dev/powershell-automation-for-1password

**Comment by wsuhoey** [comment]
Confirmed the issue no longer happens with v2.0.0 on PSGallery. Thank you!
